<a href="https://colab.research.google.com/github/mzaheen610/Machine-Learning/blob/main/SVD_Low_rank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**SVD** Implementation example using python and **numpy**

---
Formula for SVD of an mxn matrix **A**.

#       A = U∑Vᵀ
  
Where,

U = Orthogonal mxm matrix with eigenvectors of AAᵀ as its columns

V = Orthogonal nxn matrix with eigenvectors of AAᵀ as its columns

Σ = Diagonal matrix with singular values as the diagonal elements.

Λ = Eigenvectors of **AAᵀ**/**AᵀA**

σ = Λ½ (Singular Value of A)

In [ ]:
import numpy as np
np.set_printoptions(precision=3)

In [ ]:
A = np.array([[1,2,3,4],[1,1,2,3],[0,1,1,0]])
print(A)
print(f"Dimension of A : {A.shape}")

u,s,vh = np.linalg.svd(A)
print(f"U : {u}")
print(f"S : {s}")
print(f"V : {vh}")


[[1 2 3 4]
 [1 1 2 3]
 [0 1 1 0]]
Dimension of A : (3, 4)
U : [[ 0.81  0.09 -0.58]
 [ 0.57 -0.35  0.74]
 [ 0.13  0.93  0.34]]
S : [6.75 1.17 0.22]
V : [[ 0.2   0.34  0.55  0.73]
 [-0.22  0.66  0.44 -0.57]
 [ 0.76 -0.34  0.42 -0.36]
 [-0.58 -0.58  0.58  0.  ]]


Here Sigma is given as a 3 element numpy array. (It should have a size of mxn.)To reshape it we can use,


In [ ]:
sigma = np.diag(s)
print(sigma)
sigma.shape
b = np.zeros((3,4))
b[:3,:3] = sigma
sigma = b
print(sigma)

[[6.75 0.   0.  ]
 [0.   1.17 0.  ]
 [0.   0.   0.22]]
[[6.75 0.   0.   0.  ]
 [0.   1.17 0.   0.  ]
 [0.   0.   0.22 0.  ]]


In [ ]:

print(u.dot(u.T)) #Veryfing if U is orthogonal
print(vh.dot(vh.T)) #Veryfying if V is orthogonal

[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]
[[ 1.  0. -0.  0.]
 [ 0.  1.  0.  0.]
 [-0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


***Reconstruction of the array A from its SVD arrays:***

In [ ]:
original_matrix = np.dot(np.dot(u,sigma),vh)
print(original_matrix, "\n\nSuccess!")

[[ 1.  2.  3.  4.]
 [ 1.  1.  2.  3.]
 [ 0.  1.  1. -0.]] 

Success!


To calculate the 2-rank approximation of A, we have to reduce the number of singular values in sigma to 2.

Then,

sigma will be a 2x2 matrix,

u - 3x2 matrix

v - 2x4 matrix



In [ ]:
# print(s)
s = [6.75, 1.17]
sigma = np.zeros((2,2))
sigma[:2,:2] = np.diag(s)
print(sigma)
#slicing u and v
u = u[:,:2]
vh = vh[:2,:]
print(u)
print(vh)
print(u.shape, sigma.shape, vh.shape)

[[6.75 0.  ]
 [0.   1.17]]
[[ 0.81  0.09]
 [ 0.57 -0.35]
 [ 0.13  0.93]]
[[ 0.2   0.34  0.55  0.73]
 [-0.22  0.66  0.44 -0.57]]
(3, 2) (2, 2) (2, 4)


Then the Low rank (ie 2 rank) approximation of A will be:

In [ ]:
A = np.dot(np.dot(u,sigma),vh)
print(A)

[[ 1.096  1.956  3.052  3.954]
 [ 0.876  1.056  1.932  3.058]
 [-0.055  1.023  0.968  0.028]]
